name: italo
version: v4.0.2
summary: "Italo: XTRI: Private digital asset building stability into value storage https://xtri.network"
description: |
    Cryptocurrencies are inherently volatile. 
    And while centralized stablecoins like Tether can provide value stability, 
    they require trust of a third party to honor redemption.
    In contrast to Tether, Italo (XTRI) is an attempt to build
    the first private and decentralized stablecoin the Sao Dollar (SAO).
grade: devel
confinement: strict

apps:
    italod:
        daemon: forking
        command: |
          italod-wrapper --detach --data-dir ${SNAP_COMMON} --config-file ${SNAP_USER_DATA}/etc/italod.conf
        plugs:
            - network
            - network-bind
    italo-wallet-rpc:
        command: |
          italo-wallet-rpc --log-file ${SNAP_USER_DATA}
        plugs:
            - home
            - network
            - network-bind
    italo-wallet-cli:
        command: |
          italo-wallet-cli --log-file ${SNAP_USER_DATA}
        plugs:
            - home
            - network

parts:
    cmake-build:
        plugin: cmake
        configflags:
            - -DBDB_STATIC=1
            - -DBoost_USE_STATIC_LIBS=1
            - -DBoost_USE_STATIC_RUNTIME=1
            - -DARCH=default
        source: .
        build-packages:
            - gcc
            - pkg-config
            - libunbound-dev
            - libevent-dev
            - libboost-all-dev
            - libzmqpp-dev
            - libzmq3-dev
            - libsodium-dev
            - libdb-dev
            - libunwind-dev
            - libminiupnpc-dev
            - libldns-dev
            - libexpat1-dev
            - libreadline6-dev
            - bison
            - doxygen
            - graphviz
        stage-packages:
            - libminiupnpc10
            - libunbound2
            - libunwind8
        prime:
            - bin
            - usr/lib/
            - -usr/lib/gcc
            - -usr/share

    dist-files:
        plugin: dump
        source: .
        organize:
            contrib/snap/italod.conf: etc/italod.conf
            contrib/snap/italod-wrapper: bin/italod-wrapper
        prime:
            - etc
            - bin
